### ISSUE TITLE
Error in line 701 of skbuild.setuptools_wrap when installing in development mode

### ISSUE THREAD

**Issue by romankempt** [practicalci/cookiecutter-cpp#14]
**Describe the bug**
Installing a project via `pip install .` works, but fails when trying to install in development mode (either `pip install -e .` or `python setup.py develop`).

The error is triggered here:
```
Traceback (most recent call last):
  File "/mnt/c/Users/rkempt/Repositories/hetbuilder/setup.py", line 39, in <module>
    setup(
  File "/home/rkempt/miniconda3/envs/hetbuilder/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 701, in setup
    package_file = os.path.join(package_dir[package], package_file)
KeyError: ''
```

The source code of the relevant function is here:

```python
    if developer_mode:
        # Copy packages
        for package, package_file_list in package_data.items():
            for package_file in package_file_list:
                package_file = os.path.join(package_dir[package], package_file)
                cmake_file = os.path.join(CMAKE_INSTALL_DIR(), package_file)
                if os.path.exists(cmake_file):
                    _copy_file(cmake_file, package_file, hide_listing)
```

I suspect some package variable is not set correctly for development mode?

**To Reproduce**

My `setup.py` looks like this:

```python
setup(
    name="hetbuilder",
    version=version,
    author="Roman Kempt",
    author_email="roman.kempt@tu-dresden.de",
    description="A tool to build heterostructure interfaces based on coincidence lattice theory.",
    long_description=long_description,
    license="MIT",
    url="https://github.com/romankempt/hetbuilder.git",
    download_url="https://github.com/romankempt/hetbuilder.git",
    packages=find_packages(),
    package_data={"": ["*.xyz", "CMakeLists.txt"]},
    # package_dir={"": ""},
    cmake_install_dir="hetbuilder",
    include_package_data=True,
    scripts=["bin/hetbuilder"],
    install_requires=[
        "numpy",
        "scipy",
        "spglib",
        "matplotlib",
        "ase",
        "networkx",
        "pretty_errors",
        "rich",
        "typer",
        "pybind11",
    ],
    classifiers=[
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: C++",
        "Topic :: Scientific/Engineering :: Chemistry",
        "Topic :: Scientific/Engineering :: Physics",
    ],
    cmake_args=[
        "-DCMAKE_BUILD_TYPE={}".format("RELEASE"),  # not used on MSVC, but no harm,
    ],
    zip_safe=False,
)
```

**Expected behavior**
A development installation in the source directory.

**Desktop (please complete the following information):**
 - OS: WSL2

**Comment by romankempt** [comment]
gosh, opened issue in the wrong tab -sorry

**Comment by mjscosta** [comment]
@romankempt did you build it previously with CMake ? I'm not sure that skbuild supports dev mode, you'd need to keep the C++ libraries/native build python packages in sych with the code ... 

Typical dev mode for python code, just ends up creating a symbolic link from the installed python package to the source code, when building native code, that wont work ...

**Comment by mjscosta** [comment]
How I'd aproach the issue, would be having something like a fswatch command, checking for changes to the source C++ code, and rerun pip install on the package ... maybe with some kind of lag to avoid having the CMake running all the time you save a file ...

**Comment by romankempt** [comment]
sorry, I accidentally opened the issue in your github repo because I was looking at it as a template. I've opened the github issue in the scikit-build repository, where it belongs - this one can be deleted
